package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
)

// renameMap 收集 type 原始全名 → 新全名 的映射 (仅 unlocked 且有建议的)。
func renameMap(mod *Module) map[string]string {
	out := map[string]string{}
	for _, t := range mod.Types {
		if !t.Rename.Locked && t.Rename.Best() != nil {
			out[t.OriginalFullName()] = t.FullName()
		}
	}
	return out
}

// rewriteTypeRef 在一个类型字符串中, 把所有出现过的原始全名替换为新名。
// 按长度降序替换避免前缀遮蔽 (UnityEngine.X 不会先被 UnityEngine 之类的吃掉)。
func rewriteTypeRef(s string, m map[string]string) string {
	if len(m) == 0 {
		return s
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Slice(keys, func(i, j int) bool { return len(keys[i]) > len(keys[j]) })
	for _, k := range keys {
		s = strings.ReplaceAll(s, k, m[k])
	}
	return s
}

func annotate(r *Renameable) string {
	if r.Locked {
		return ""
	}
	b := r.Best()
	if b == nil {
		return ""
	}
	return fmt.Sprintf("  /* obf: %s (conf=%.2f %s) */", r.Original, b.Confidence, b.Reason)
}

func methodKeywords(m *Method) string {
	parts := []string{}
	if m.IsPublic {
		parts = append(parts, "public")
	}
	if m.IsStatic {
		parts = append(parts, "static")
	}
	if m.IsAbstract {
		parts = append(parts, "abstract")
	} else if m.IsVirtual {
		parts = append(parts, "virtual")
	}
	if m.IsOverride {
		parts = append(parts, "override")
	}
	if len(parts) == 0 {
		return "private"
	}
	return strings.Join(parts, " ")
}

// RenderDumpCS 生成可读的 dump.cs 文本。
func RenderDumpCS(mod *Module) string {
	rm := renameMap(mod)
	var sb strings.Builder
	sb.WriteString("// Generated by beautiful_dump\n")
	sb.WriteString("// 注释 /* obf: ... */ 标记为重命名建议, 原始混淆名保留供对照\n\n")

	byNS := map[string][]*Type{}
	for _, t := range mod.Types {
		byNS[t.Namespace] = append(byNS[t.Namespace], t)
	}
	namespaces := make([]string, 0, len(byNS))
	for k := range byNS {
		namespaces = append(namespaces, k)
	}
	sort.Strings(namespaces)

	for _, ns := range namespaces {
		types := byNS[ns]
		indent := ""
		if ns != "" {
			fmt.Fprintf(&sb, "namespace %s {\n", ns)
			indent = "    "
		}
		for _, t := range types {
			kind := "class"
			switch {
			case t.IsInterface:
				kind = "interface"
			case t.IsEnum:
				kind = "enum"
			case t.IsValueType:
				kind = "struct"
			}
			mods := []string{}
			if t.IsAbstract && !t.IsInterface {
				mods = append(mods, "abstract")
			}
			decl := strings.Join(append(mods, kind, t.Rename.Display()), " ")
			if t.BaseType != "" || len(t.Interfaces) > 0 {
				inh := []string{}
				if t.BaseType != "" {
					inh = append(inh, rewriteTypeRef(t.BaseType, rm))
				}
				for _, i := range t.Interfaces {
					inh = append(inh, rewriteTypeRef(i, rm))
				}
				decl += " : " + strings.Join(inh, ", ")
			}
			fmt.Fprintf(&sb, "%s%s {%s\n", indent, decl, annotate(&t.Rename))

			for fi := range t.Fields {
				f := &t.Fields[fi]
				kw := "private"
				if f.IsPublic {
					kw = "public"
				}
				if f.IsStatic {
					kw += " static"
				}
				ftype := rewriteTypeRef(f.Type, rm)
				fmt.Fprintf(&sb, "%s    %s %s %s;%s\n", indent, kw, ftype, f.Rename.Display(), annotate(&f.Rename))
			}

			if len(t.Fields) > 0 && len(t.Methods) > 0 {
				sb.WriteString("\n")
			}

			for mi := range t.Methods {
				m := &t.Methods[mi]
				rt := rewriteTypeRef(m.ReturnType, rm)
				params := make([]string, 0, len(m.Parameters))
				for _, p := range m.Parameters {
					nm := p.Name
					if nm == "" {
						nm = "_"
					}
					params = append(params, fmt.Sprintf("%s %s", rewriteTypeRef(p.Type, rm), nm))
				}
				var sig string
				if m.IsConstructor {
					sig = fmt.Sprintf("%s %s(%s)", methodKeywords(m), t.Rename.Display(), strings.Join(params, ", "))
				} else {
					sig = fmt.Sprintf("%s %s %s(%s)", methodKeywords(m), rt, m.Rename.Display(), strings.Join(params, ", "))
				}
				rva := ""
				if m.RVA != nil {
					rva = fmt.Sprintf("  // RVA 0x%X", *m.RVA)
				}
				fmt.Fprintf(&sb, "%s    %s { }%s%s\n", indent, sig, rva, annotate(&m.Rename))
			}
			fmt.Fprintf(&sb, "%s}\n\n", indent)
		}
		if ns != "" {
			sb.WriteString("}\n\n")
		}
	}
	return sb.String()
}

// WriteDumpCS 把 dump.cs 写到磁盘。
func WriteDumpCS(mod *Module, path string) error {
	return os.WriteFile(path, []byte(RenderDumpCS(mod)), 0o644)
}

type symbolMapField struct {
	Original   string  `json:"original"`
	Renamed    string  `json:"renamed"`
	Confidence float64 `json:"confidence"`
	Reason     string  `json:"reason"`
	Type       string  `json:"type"`
}

type symbolMapMethod struct {
	Original   string  `json:"original"`
	Renamed    string  `json:"renamed"`
	Confidence float64 `json:"confidence"`
	Reason     string  `json:"reason"`
	Signature  string  `json:"signature"`
	RVA        *int64  `json:"rva,omitempty"`
}

type symbolMapType struct {
	Original   string   `json:"original"`
	Renamed    *string  `json:"renamed"`
	Confidence *float64 `json:"confidence"`
	Reason     *string  `json:"reason"`
	Role       string   `json:"role,omitempty"`
}

type symbolMapEntry struct {
	Type    symbolMapType     `json:"type"`
	Fields  []symbolMapField  `json:"fields"`
	Methods []symbolMapMethod `json:"methods"`
}

type symbolMap struct {
	Types []symbolMapEntry `json:"types"`
}

// BuildSymbolMap 构造可序列化的符号映射结构。
func BuildSymbolMap(mod *Module) symbolMap {
	out := symbolMap{}
	for _, t := range mod.Types {
		entry := symbolMapEntry{Type: symbolMapType{Original: t.OriginalFullName(), Role: t.Role}}
		if b := t.Rename.Best(); b != nil && !t.Rename.Locked {
			fn := t.FullName()
			conf := b.Confidence
			reason := b.Reason
			entry.Type.Renamed = &fn
			entry.Type.Confidence = &conf
			entry.Type.Reason = &reason
		}
		for fi := range t.Fields {
			f := &t.Fields[fi]
			b := f.Rename.Best()
			if b == nil {
				continue
			}
			entry.Fields = append(entry.Fields, symbolMapField{
				Original: f.Rename.Original, Renamed: f.Rename.Display(),
				Confidence: b.Confidence, Reason: b.Reason, Type: f.Type,
			})
		}
		for mi := range t.Methods {
			m := &t.Methods[mi]
			b := m.Rename.Best()
			if b == nil {
				continue
			}
			entry.Methods = append(entry.Methods, symbolMapMethod{
				Original: m.Rename.Original, Renamed: m.Rename.Display(),
				Confidence: b.Confidence, Reason: b.Reason,
				Signature: m.Signature(), RVA: m.RVA,
			})
		}
		if entry.Type.Renamed != nil || len(entry.Fields) > 0 || len(entry.Methods) > 0 {
			out.Types = append(out.Types, entry)
		}
	}
	return out
}

// WriteSymbolMap 把符号映射写为 JSON 文件。
func WriteSymbolMap(mod *Module, path string) error {
	data, err := json.MarshalIndent(BuildSymbolMap(mod), "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, data, 0o644)
}
